src/tests: Fix only GTK3 builds
Add TEST_GTK_VERSION environment.
Also fix ibus-compose test failure to unset NO_LOAD_COMPOSE_FILE.

BUG=https://github.com/ibus/ibus/issues/2859

diff --git a/src/tests/runtest b/src/tests/runtest
--- a/src/tests/runtest
+++ b/src/tests/runtest
@@ -23,6 +23,7 @@
 : ${srcdir:=.}
 : ${DISABLE_GUI_TESTS:=''}
 : ${DISABLE_DAEMONIZE_IN_TESTS:=''}
+: ${TEST_GTK_VERSION:=0}
 
 BUS_REQUIRED_TESTS="
 ibus-bus
@@ -140,30 +141,38 @@ run_test_case()
         IBUS_ADDRESS_FILE=$PWD/ibus-daemon.pid
         export IBUS_ADDRESS_FILE
 
-        if test -f "../$top_builddir/client/gtk4/.libs/libim-ibus.so" ; then
-            IM_IBUS_SO="../$top_builddir/client/gtk4/.libs/libim-ibus.so"
-        elif test -f "../$top_builddir/client/gtk4/libim-ibus.so" ; then
-            IM_IBUS_SO="../$top_builddir/client/gtk4/libim-ibus.so"
-        else
-            echo "NOT FOUND $top_builddir/client/gtk4/libim-ibus.so"
+        case $TEST_GTK_VERSION in
+        4)
+            if test -f "../$top_builddir/client/gtk4/.libs/libim-ibus.so" ; then
+                IM_IBUS_SO="../$top_builddir/client/gtk4/.libs/libim-ibus.so"
+            elif test -f "../$top_builddir/client/gtk4/libim-ibus.so" ; then
+                IM_IBUS_SO="../$top_builddir/client/gtk4/libim-ibus.so"
+            else
+                echo "NOT FOUND $top_builddir/client/gtk4/libim-ibus.so"
+                exit 1
+            fi
+            mkdir -p "$PWD/lib/gtk-4.0/immodules"
+            cp "$IM_IBUS_SO" "$PWD/lib/gtk-4.0/immodules/."
+            export GTK_EXE_PREFIX="$PWD"
+            ;;
+        3)
+            if test -f "../$top_builddir/client/gtk3/.libs/im-ibus.so" ; then
+                IM_IBUS_SO="../$top_builddir/client/gtk3/.libs/im-ibus.so"
+            elif test -f "../$top_builddir/client/gtk3/im-ibus.so" ; then
+                IM_IBUS_SO="../$top_builddir/client/gtk3/im-ibus.so"
+            else
+                echo "NOT FOUND $top_builddir/client/gtk3/im-ibus.so"
+                exit 1
+            fi
+            GTK_IM_MODULE_FILE=$PWD/imcache
+            export GTK_IM_MODULE_FILE
+            $GTK_QUERY_MODULE "$IM_IBUS_SO" > $GTK_IM_MODULE_FILE
+            ;;
+        *)
+            echo "NOT SUPPORT GTK_VERSION $TEST_GTK_VERSION"
             exit 1
-        fi
-        mkdir -p "$PWD/lib/gtk-4.0/immodules"
-        cp "$IM_IBUS_SO" "$PWD/lib/gtk-4.0/immodules/."
-        export GTK_EXE_PREFIX="$PWD"
-
-        if test -f "../$top_builddir/client/gtk3/.libs/im-ibus.so" ; then
-            IM_IBUS_SO="../$top_builddir/client/gtk3/.libs/im-ibus.so"
-        elif test -f "../$top_builddir/client/gtk3/im-ibus.so" ; then
-            IM_IBUS_SO="../$top_builddir/client/gtk3/im-ibus.so"
-        else
-            echo "NOT FOUND $top_builddir/client/gtk3/im-ibus.so"
-            exit 1
-        fi
-
-        GTK_IM_MODULE_FILE=$PWD/imcache
-        export GTK_IM_MODULE_FILE
-        $GTK_QUERY_MODULE "$IM_IBUS_SO" > $GTK_IM_MODULE_FILE
+            ;;
+        esac
 
         cp "../$top_srcdir/data/dconf/$IBUS_SCHEMA_FILE" $PWD
         glib-compile-schemas $PWD
@@ -235,6 +244,8 @@ else
         if test x"$first" = x"#" ; then
             continue
         fi
+        unset NO_LOAD_COMPOSE_FILE
+        unset COMPOSE_FILE
         export $e
         echo "Run `func_basename $tst` on $e"
         echo "======================="
